SELECT
    CAST(SESSION_ID AS STRING) AS SESSION_ID,
    CAST(ITEM_NAME AS STRING) AS ITEM_NAME,
    ITEM_VIEW_AT AS ITEM_VIEW_AT_TS,
    CAST(ADD_TO_CART_QUANTITY AS NUMBER) AS ADD_TO_CART_QUANTITY,
    CAST(REMOVE_FROM_CART_QUANTITY AS NUMBER) AS REMOVE_FROM_CART_QUANTITY,
    CAST(PRICE_PER_UNIT AS DECIMAL(18,2)) AS PRICE_PER_UNIT
from {{ source('web', 'ITEM_VIEWS') }}