SELECT
    CAST(ORDER_ID AS STRING) AS ORDER_ID,
    CAST(SESSION_ID AS STRING) AS SESSION_ID,
    CAST(CLIENT_NAME AS STRING) AS CLIENT_NAME,
    ORDER_AT AS ORDER_AT_TS,
    CAST(PAYMENT_METHOD AS STRING) AS PAYMENT_METHOD,
    CAST(PAYMENT_INFO AS STRING) AS PAYMENT_INFO,
    CAST(SHIPPING_ADDRESS AS STRING) AS SHIPPING_ADDRESS,
    TRY_TO_DECIMAL(SHIPPING_COST, 18, 2) AS SHIPPING_COST,
    CAST(STATE AS STRING) AS STATE,
    CAST(PHONE AS STRING) AS PHONE,
    CAST(TAX_RATE AS FLOAT) AS TAX_RATE
FROM {{ source('web', 'ORDERS') }}